CREATE TABLE IF NOT EXISTS TaskOption (
    id BIGINT AUTO_INCREMENT NOT NULL ,
    task_id BIGINT NOT NULL,
    option_text VARCHAR(255) NOT NULL,
    isCorrect BOOLEAN NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (task_id) REFERENCES Task(id) ON DELETE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;